# syntax=docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.1.4
# Update RubyGems to a specific version, latest valid for Ruby version 3.1.x
ARG RUBYGEMS_VERSION=3.6.9

### 1 base stage
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /opt/roadmap

# Install 
#   Update RubyGems to a specific version
#   base packages
#   packages needed to build gems
RUN apt-get update -qq && \
  gem update --system ${RUBYGEMS_VERSION} --no-document && \
  apt-get install --no-install-recommends -y \
    curl libjemalloc2 libpq-dev postgresql-client libmariadb-dev mariadb-client libvips openssl libjpeg62-turbo libpng16-16 imagemagick libxrender1 libxext6 \
    build-essential git pkg-config libyaml-dev libxml2-dev libssl-dev vim bison nodejs yarnpkg && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN ln -s /usr/bin/yarnpkg /usr/bin/yarn
