services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dmponline
    container_name: dmponline
    volumes:
      - ./log:/opt/roadmap/log
    environment:
      - DB_ADAPTER=${DB_ADAPTER:-mysql2}
      - DB_NAME=${DB_NAME:?DB_NAME must be set}
      - DB_USERNAME=${DB_USERNAME:?DB_USERNAME must be set}
      - DB_PASSWORD=${DB_PASSWORD:?DB_PASSWORD must be set}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_POOL=${DB_POOL:-16}
      - MALLOC_ARENA_MAX=${MALLOC_ARENA_MAX:-2}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT:-true}
      - DMP_LOCAL_LOGIN=${DMP_LOCAL_LOGIN:-true}
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES:-false}
      - EXECJS_RUNTIME=Node
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-0}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-1}
      - DMP_SMTP_ADDRESS=mail
      - DMP_SMTP_PORT=1025
      - BINDING=0.0.0.0
      - BELNET_SPLITTED_LOGS=${BELNET_SPLITTED_LOGS:-false}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:?SECRET_KEY_BASE must be set}
      - BELNET_DRAGONFLY_SECRET=${BELNET_DRAGONFLY_SECRET:?BELNET_DRAGONFLY_SECRET must be set}
      - BELNET_DEVISE_PEPPER=${BELNET_DEVISE_PEPPER:?BELNET_DEVISE_PEPPER must be set}
      - DMP_ENVIRONMENT=${DMP_ENVIRONMENT:?DMP_ENVIRONMENT must be set}
      - DMP_ENVIRONMENT_COLOR_CODE=${DMP_ENVIRONMENT_COLOR_CODE:?DMP_ENVIRONMENT_COLOR_CODE must be set}
      - BELNET_DMPONLINE_VERSION=${BELNET_DMPONLINE_VERSION:?BELNET_DMPONLINE_VERSION must be set}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: "0.0.0.0"
      MYSQL_DATABASE: roadmap_development
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql

  mail:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - 8025:8025
