services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    working_dir: "/opt/roadmap"
    volumes:
      - .:/opt/roadmap
    container_name: roadmap-dev
    env_file:
      - path: '/opt/roadmap/.env'
        required: false
    environment:
      - MALLOC_ARENA_MAX=${MALLOC_ARENA_MAX:-2}
      - RAILS_LOG_TO_STDOUT=${RAILS_LOG_TO_STDOUT:-true}
      - DMP_LOCAL_LOGIN=${DMP_LOCAL_LOGIN:-true}
      - DB_ADAPTER=${DB_ADAPTER:-mysql2}
      - DB_PASSWORD=${DB_PASSWORD:-root}
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=${RAILS_SERVE_STATIC_FILES:-false}
      - EXECJS_RUNTIME=Node
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-0}
      - RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-1}
      - DMP_SMTP_ADDRESS=mail
      - DMP_SMTP_PORT=1025
      - BUNDLE_PATH=vendor/bundle
      - BINDING=0.0.0.0
      - BUNDLE_PATH=vendor/bundle
      - BUNDLE_WITH=mysql:puma:development:test:ci
      - BUNDLE_WITHOUT=aws
    entrypoint: "./entrypoint-dev.sh"
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: "0.0.0.0"
      MYSQL_DATABASE: roadmap_development
    ports:
      - 3307:3306
    volumes:
      - ./tmp/mysql:/var/lib/mysql

  mail:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - 8025:8025
