# syntax=docker/dockerfile:1
FROM ruby:3.1.4

WORKDIR /opt/roadmap

RUN apt-get update && apt-get -y install vim libpq5 libmariadb3 libyaml-0-2 libxml2 openssl bison libjpeg62-turbo libpng16-16 imagemagick libxrender1 libxext6 nodejs yarnpkg
