#!/usr/bin/env bash
set -e

# $POSTGRES_USER and $POSTGRES_DB are set in the Dockerfile, default `postgres` user and database
# Alter roles and grant privileges, via postgres superuser
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL2
  \c $DB_NAME
  CREATE SCHEMA IF NOT EXISTS $DB_USERNAME AUTHORIZATION $DB_USERNAME;
  GRANT CONNECT ON DATABASE $DB_NAME TO $DB_USERNAME;
  GRANT ALL PRIVILEGES ON SCHEMA $DB_USERNAME TO $DB_USERNAME;
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $DB_USERNAME TO $DB_USERNAME;
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $DB_USERNAME TO $DB_USERNAME;
  ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_USERNAME GRANT ALL ON TABLES TO $DB_USERNAME;
  ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_USERNAME GRANT ALL ON SEQUENCES TO $DB_USERNAME;
  REVOKE ALL ON DATABASE $DB_NAME FROM public;
  REVOKE ALL ON SCHEMA public FROM public;
EOSQL2

if [ -n "$DB2_NAME" ]; then

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL3
  \c $DB2_NAME
  CREATE SCHEMA IF NOT EXISTS $DB_USERNAME AUTHORIZATION $DB_USERNAME;
  GRANT CONNECT ON DATABASE $DB2_NAME TO $DB_USERNAME;
  GRANT ALL PRIVILEGES ON SCHEMA $DB_USERNAME TO $DB_USERNAME;
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $DB_USERNAME TO $DB_USERNAME;
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA $DB_USERNAME TO $DB_USERNAME;
  ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_USERNAME GRANT ALL ON TABLES TO $DB_USERNAME;
  ALTER DEFAULT PRIVILEGES IN SCHEMA $DB_USERNAME GRANT ALL ON SEQUENCES TO $DB_USERNAME;
  REVOKE ALL ON DATABASE $DB2_NAME FROM public;
  REVOKE ALL ON SCHEMA public FROM public;
EOSQL3

fi
